### ISSUE TITLE
pub.get error for lit_firebase_auth

### ISSUE THREAD

**Issue by azaman2204** [funwithflutter/lit_firebase_auth#21]
Because lit_firebase_auth >=0.2.0 depends on firebase_core ^0.4.5 and xxxx depends on firebase_core ^0.5.0, lit_firebase_auth >=0.2.0 is forbidden.
So, because xxxx depends on lit_firebase_auth ^0.2.3, version solving failed.
pub get failed (1; So, because xxxx. depends on lit_firebase_auth ^0.2.3, version solving failed.)

Any help much appreciated. Thanks

**Comment by sultanmyrza** [comment]
Have same issue

**Comment by uaraven** [comment]
It looks like master branch is already updated to use firebase_core v0.5 and firebase_auth v0.18, it's just not released yet and so not on pub.dev.

As a temporary workaround I tried to add dependency on github repo directly. Seems to work for me. YMMV.

In pubspec.yml:
```
  lit_firebase_auth:
    git:
      url: git://github.com/funwithflutter/lit_firebase_auth.git
```

**Comment by funwithflutter** [comment]
This is now resolved in the latest version. Please update to v0.3.0 or above. Please note that this has a number of breaking changes.
