### ISSUE TITLE
Support more authentication provider Facebook

### ISSUE THREAD

**Issue by songcamhoi** [funwithflutter/lit_firebase_auth#22]
I think login via Facebook is an important upgrade. thank

**Comment by funwithflutter** [comment]
For now, adding direct support for Facebook will be a bit hard. But I'll create an example showing how you can do it yourself.

**Comment by songcamhoi** [comment]
> For now, adding direct support for Facebook will be a bit hard. But I'll create an example showing how you can do it yourself.

thank you
