### ISSUE TITLE
Auth Related Extensions not available

### ISSUE THREAD

**Issue by Purus** [funwithflutter/lit_firebase_auth#29]
First, please accept my thanks. This package is soo cool. Thanks very much.

For some reasons, I am not able to see any of the extension methods on the BuildContext. Please let me know what I am missing.

```
context.signOut();
```

I am using latest version of tools.

```
    • Flutter version 1.22.5 at H:\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
 ```

Should I use `LitAuthInit`  class in every widget/screen classes to make use of the extension methods? Sorry if this is a beginners question.

**Comment by gabber235** [comment]
Make sure you import the class 
```dart
import 'package:lit_firebase_auth/lit_firebase_auth.dart';
```
Then flutter knows where the extension should come from. You should do this in every file that you want to use any extension.
