### ISSUE TITLE
Pub.dev version is not the same as in the GitHub Repo

### ISSUE THREAD

**Issue by Butzlabben** [funwithflutter/lit_firebase_auth#3]
In the GitHub Report, this is the code for the label of the 'Sign In anonymously' button:
`Text(
              defaultLabel,
              style: TextStyle(
                fontSize: defaultFontSize,
                fontWeight: defaultFontWeight,
              ),
            ),`
However, the version used downloaded from pub.dev is the following, including a spelling mistake:
`Text(
              'Sing in anonymously',
              style: TextStyle(
                fontSize: defaultFontSize,
                fontWeight: defaultFontWeight,
              ),
            ),`

**Comment by funwithflutter** [comment]
Thanks for spotting this. Fixed in the newer version. The naming has changed to 'Continue with...' but please not that you can override the default title.
