### ISSUE TITLE
[Enhancement] Get user details of the logged in user

### ISSUE THREAD

**Issue by Imgkl** [funwithflutter/lit_firebase_auth#5]
First of all, this package is so LIT. Kudos to the dev.

```
 User user = context.getSignedInUser();
 print(user);
```
The above code gives me just a `User(user: FirebaseUser(Instance of 'PlatformUser'))`, But Is it possible to get individual data about the user, like display name or email?

```
 User user = context.getSignedInUser();
 print(user.email);
```
should give me, email id of the logged-in user.

**Comment by funwithflutter** [comment]
Thanks for the kudos 👍 
Sorry this is a documentation issue. After all of the features are added I'll put in more effort to improve the docs. The package uses Freezed for unions. So depending on the status of the user you'll get a different state: empty, initializing, or success. If the user is signed in you'll get the `FirebaseUser`.

```dart
User user = context.getSignedInUser();
user.map(
      (value) => print(value.user.email),
      empty: (_) {},
      initializing: (_) {},
    );
```

The `value.user` is the FirebaseUser object. The FlutterFire plugins have recently gone through a massive overall. So expect some changes to this package - especially naming, as I believe the FlutterFire plugins now use User and not FirebaseUser. I'm open to suggestions to make the process easier, or more intuitive.

**Comment by funwithflutter** [comment]
Documentation updated.
