### ISSUE TITLE
Compatibility with cloud_firestore@0.14.0

### ISSUE THREAD

**Issue by CiriousJoker** [funwithflutter/lit_firebase_auth#8]
Not sure if it's the right time to upgrade, but 0.14.0 exists now, so I guess at some point it will be.

**Comment by funwithflutter** [comment]
Yes, definitely. This is a top priority to get the package to use the latest FlutterFire packages.

**Comment by CiriousJoker** [comment]
Since I suddenly needed this, I created a fork and made the changes. Do you want me to create a PR for this?

It's slightly breaking, since I had to rename User to LitUser because freezed doesn't support prefixes. https://github.com/rrousselGit/freezed/issues/70

**Comment by funwithflutter** [comment]
> Since I suddenly needed this, I created a fork and made the changes. Do you want me to create a PR for this?
> 
> It's slightly breaking, since I had to rename User to LitUser because freezed doesn't support prefixes. [rrousselGit/freezed#70](https://github.com/rrousselGit/freezed/issues/70)

Yes, definitely make a pull request! In hindsight it might be better to just return the FirebaseAuth User, instead of mapping to a new User. But for now, you can rename it to LitUser. Thanks 😀
